### ISSUE TITLE
Do not render element wrapper for falsy children

### ISSUE THREAD

**Issue by andrei-gheorghiu** [mxmul/react-packed-grid#3]
Currently the lib wraps each child in a wrapper which enforces the styling. However, since React doesn't render `null` children, `<PackedGrid />` shouldn't, either.

Repro here: https://codesandbox.io/s/grid-16-9-ratio-forked-fk51mg?file=/src/App.js

**Comment by mxmul** [comment]
Seems reasonable – open to a PR!
